config/routes.rb
Rps::Application.routes.draw do
  resources :games

  root 'games#index'
  post '/throw/', to: 'games#throw', as: 'throw'

end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	def throw
		sign_hash = {0 => :rock, 1 => :paper, 2 => :scissors}
		win_hash = {:rock => :scissors, :paper => :rock, :scissors => :paper}
		@player_throw = params[:game][:sign].to_sym
		@server_throw = sign_hash[rand(0..2)]

		if win_hash.keys.include?(@player_throw)
			#if @player_throw == @server_throw
			#	@result = 'tie'
			#elsif win_hash[@player_throw] == @server_throw
			#	@result = 'win'
			#else
			#	@result = 'lose'
			#end
			@result = @player_throw == @server_throw ? 'tie' : win_hash[@player_throw] == @server_throw ? 'win' : 'lose'
		else
			@result = 'invalid'
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<%= form_for :game, url: throw_path do |f| %>
<p>
	<%= f.select :sign, ['rock', 'paper', 'scissors'] %>
</p>
<%= f.submit %>
<% end %>

app/views/games/throw.html.erb
<div class="<%= @result %>">
	<h1>
		<%= @result.upcase %>
	</h1>
<br/>
<%= link_to 'New Game', root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rock-Paper-Scissors</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>